/** @type {import('tailwindcss').Config} */
export default {
  content: ["./build/views/**/*.{html,js}"],
  theme: {
    extend: {},
  },
  plugins: [require("daisyui")],
  daisyui: {
    themes: [
      {
        shopify: {
          "primary": "#006e52",
          "secondary": "#2a2a2a",
          "accent": "#d9f99d",
          "neutral": "#fff",
          "base-100": "#fff",
          "info": "#bae6fd",
          "success": "#d9f99d",
          "warning": "#fef08a",        
          "error": "#f43f5e",
        },
      },
      "dark",
      "cupcake",
      "light",
      "dark",
      "cupcake",
      "bumblebee",
      "emerald",
      "corporate",
      "synthwave",
      "retro",
      "cyberpunk",
      "valentine",
      "halloween",
      "garden",
      "forest",
      "aqua",
      "lofi",
      "pastel",
      "fantasy",
      "wireframe",
      "black",
      "luxury",
      "dracula",
      "cmyk",
      "autumn",
      "business",
      "acid",
      "lemonade",
      "night",
      "coffee",
      "winter",
    ],
  },
};
